name: LeetCode Golang Solution Testing

on: 
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [ '1.21' ] # Specify a recent Go version
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2 # Use a newer version of actions/setup-go
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code
      uses: actions/checkout@v2 # Use a newer version of actions/checkout

    - name: Download dependencies
      run: go mod download

    - name: Testing
      run: go test -cover ./...